export const lightThemes = [
  { name: 'Catppuccin Latte', id: 'catppuccin-latte' },
  { name: 'Everforest Light', id: 'everforest-light' },
  { name: 'GitHub Light', id: 'github-light' },
  { name: 'GitHub Light Default', id: 'github-light-default' },
  { name: 'GitHub Light High Contrast', id: 'github-light-high-contrast' },
  { name: 'Kanagawa Lotus', id: 'kanagawa-lotus' },
  { name: 'Light Plus', id: 'light-plus' },
  { name: 'Material Theme Lighter', id: 'material-theme-lighter' },
  { name: 'Min Light', id: 'min-light' },
  { name: 'One Light', id: 'one-light' },
  { name: 'Rosé Pine Dawn', id: 'rose-pine-dawn' },
  { name: 'Slack Ochin', id: 'slack-ochin' },
  { name: 'Snazzy Light', id: 'snazzy-light' },
  { name: 'Solarized Light', id: 'solarized-light' },
  { name: 'Vitesse Light', id: 'vitesse-light' },
];
export const darkThemes = [
  { name: 'Andromeeda', id: 'andromeeda' },
  { name: 'Aurora X', id: 'aurora-x' },
  { name: 'Ayu Dark', id: 'ayu-dark' },
  { name: 'Catppuccin Frappé', id: 'catppuccin-frappe' },
  { name: 'Catppuccin Macchiato', id: 'catppuccin-macchiato' },
  { name: 'Catppuccin Mocha', id: 'catppuccin-mocha' },
  { name: 'Dark Plus', id: 'dark-plus' },
  { name: 'Dracula Theme', id: 'dracula' },
  { name: 'Dracula Theme Soft', id: 'dracula-soft' },
  { name: 'Everforest Dark', id: 'everforest-dark' },
  { name: 'GitHub Dark', id: 'github-dark' },
  { name: 'GitHub Dark Default', id: 'github-dark-default' },
  { name: 'GitHub Dark Dimmed', id: 'github-dark-dimmed' },
  { name: 'GitHub Dark High Contrast', id: 'github-dark-high-contrast' },
  { name: 'Houston', id: 'houston' },
  { name: 'Kanagawa Dragon', id: 'kanagawa-dragon' },
  { name: 'Kanagawa Wave', id: 'kanagawa-wave' },
  { name: 'LaserWave', id: 'laserwave' },
  { name: 'Material Theme', id: 'material-theme' },
  { name: 'Material Theme Darker', id: 'material-theme-darker' },
  { name: 'Material Theme Ocean', id: 'material-theme-ocean' },
  { name: 'Material Theme Palenight', id: 'material-theme-palenight' },
  { name: 'Min Dark', id: 'min-dark' },
  { name: 'Monokai', id: 'monokai' },
  { name: 'Night Owl', id: 'night-owl' },
  { name: 'Nord', id: 'nord' },
  { name: 'One Dark Pro', id: 'one-dark-pro' },
  { name: 'Plastic', id: 'plastic' },
  { name: 'Poimandres', id: 'poimandres' },
  { name: 'Red', id: 'red' },
  { name: 'Rosé Pine', id: 'rose-pine' },
  { name: 'Rosé Pine Moon', id: 'rose-pine-moon' },
  { name: 'Slack Dark', id: 'slack-dark' },
  { name: 'Solarized Dark', id: 'solarized-dark' },
  { name: 'Synthwave \'84', id: 'synthwave-84' },
  { name: 'Tokyo Night', id: 'tokyo-night' },
  { name: 'Vesper', id: 'vesper' },
  { name: 'Vitesse Black', id: 'vitesse-black' },
  { name: 'Vitesse Dark', id: 'vitesse-dark' },
];
export const themes = [...lightThemes, ...darkThemes];
